[tcpout]
## uncomment the line below to enable forwarding to desired destination for your scenario
#defaultGroup = splunk
#defaultGroup = cribl
#defaultGroup = cribl,splunk

[tcpout:cribl]
server = cribl-node1.example.com:9997, cribl-node2.example.com:9997
sendCookedData = true
useSSL = true
sslVerifyServerCert = true
sslVerifyServerName = true
## uncomment the lines below if you want to enable mTLS
#compressed = false
#clientCert = $SPLUNK_HOME/etc/apps/CFG_uf_forward_cribl_linux/certs/client_cert.pem
# sslPassword = <only if the private key is encrypted>


