[sslConfig]
sslRootCAPath =  $SPLUNK_HOME\etc\apps\CFG_uf_forward_cribl_windows\certs\ca\ca_cert.pem
caTrustStore = splunk

## Windows note:
## To force app-contained trust on Windows
sslRootCAPathHonoredOnWindows = true